name = "CxxCall"
uuid = "dbaf2c2e-b61b-429c-b386-57175d7288fb"
authors = ["Jan Weidner <jw3126@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CxxInterface = "62027b0a-52e9-423e-ab47-e314c210e772"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[targets]
test = ["Test", "Libdl"]
